ENV_REGISTRY = {
    "jigsaw/easy": {
        "env_kwargs": dict(
            num_rows=2,
            num_cols=2,
            sample_dir="./inference_dataset/partial_datasets/jigsaw"
        ),
        "seed_key": "seed",
        "gt_strategy": "swap",
        "extra_state": None,
    },
    "jigsaw/hard": {
        "env_kwargs": dict(
            num_rows=3,
            num_cols=3,
            sample_dir="./inference_dataset/partial_datasets/jigsaw"
        ),
        "seed_key": "seed",
        "gt_strategy": "swap",
        "extra_state": None,
    },
    "colorization/easy": {
        "env_kwargs": dict(
            sample_dir="./inference_dataset/partial_datasets/colorization",
            circle_size=20,
            accuracy_radius=11,
            max_steps=25,
            region_radius=30,
            min_brightness=25,
            max_brightness=230,
        ),
        "seed_key": "seed",
        "gt_strategy": None,
        "gt_kwargs": {},
        "extra_state": None,
    },
    "colorization/hard": {
        "env_kwargs": dict(
            sample_dir="./inference_dataset/partial_datasets/colorization",      
            circle_size=20,
            accuracy_radius=16,
            max_steps=25,
            region_radius=30,
            min_brightness=25,
            max_brightness=230,
        ),
        "seed_key": "seed",
        "gt_strategy": None,
        "gt_kwargs": {},
        "extra_state": None,
    },
    "matchstick_equation/easy": {
        "env_kwargs": dict(
            enforce_min_distance=True,
            break_moves=1,
        ),
        "seed_key": "random_seed",
        "gt_strategy": "sos",
        "gt_kwargs": dict(sos_seed=12, sos_max_len=80),
        "extra_state": None,
    },
    "matchstick_equation/hard": {
        "env_kwargs": dict(
            enforce_min_distance=True,
            break_moves=2,
        ),
        "seed_key": "random_seed",
        "gt_strategy": "sos",
        "gt_kwargs": dict(sos_seed=12, sos_max_len=80),
        "extra_state": None,
    },
    "matchstick_rotation/easy": {
        "env_kwargs": dict(
            canvas_size=(120, 120),
            stick_length=20,
            pos_tolerance=10,
            ang_tolerance=15,
        ),
        "seed_key": None,
        "gt_strategy": None,
        "gt_kwargs": dict(num_steps=3),
        "extra_state": None,
    },
    "matchstick_rotation/hard": {
        "env_kwargs": dict(
            canvas_size=(120, 120),
            stick_length=20,
            pos_tolerance=5,
            ang_tolerance=10,
        ),
        "seed_key": None,
        "gt_strategy": None,
        "gt_kwargs": dict(num_steps=3),
        "extra_state": None,
    },
    "mental_rotation_2d/easy": {
        "env_kwargs": dict(
            sample_dir="./inference_dataset/partial_datasets/2d_rotation",
            image_size=128,
            max_steps=5,
            tolerance=10.0,
        ),
        "seed_key": "seed",
        "gt_strategy": None,
        "gt_kwargs": dict(num_steps=3),
        "extra_state": None,
    },
    "mental_rotation_2d/hard": {
        "env_kwargs": dict(
            sample_dir="./inference_dataset/partial_datasets/2d_rotation",
            image_size=128,
            tolerance=5.0,
            max_steps=5,
        ),
        "seed_key": "seed",
        "gt_strategy": None,
        "gt_kwargs": dict(num_steps=3),
        "extra_state": None,
    },
    "mental_rotation_3d_cube/easy": {
        "env_kwargs": dict(
            max_steps=20,
            num_segments=4,
            action_frame="world",
        ),
        "seed_key": "seed",
        "gt_strategy": None,
        "gt_kwargs": dict(num_steps=3),
        "extra_state": None,
    },
    "mental_rotation_3d_cube/hard": {
        "env_kwargs": dict(
            max_steps=20,
            num_segments=6,
            action_frame="world",
        ),
        "seed_key": "seed",
        "gt_strategy": None,
        "gt_kwargs": dict(num_steps=3),
        "extra_state": None,
    },
    "mental_rotation_3d_objaverse/easy": {
        "env_kwargs": dict(
            render_size=128,
            sample_dir="./inference_dataset/partial_datasets/objaverse",
            tolerance=15.0,
            action_frame="world",
            use_textures=True,
        ),
        "seed_key": "seed",
        "gt_strategy": None,
        "gt_kwargs": dict(num_steps=3),
        "extra_state": None,
    },
    "mental_rotation_3d_objaverse/hard": {
        "env_kwargs": dict(
            render_size=128,
            tolerance=5.0,
            sample_dir="./inference_dataset/partial_datasets/objaverse",
            action_frame="world",
            use_textures=True,
        ),
        "seed_key": "seed",
        "gt_strategy": None,
        "gt_kwargs": dict(num_steps=3),
        "extra_state": None,
    },
    "referring_dot_pointing/easy": {
        "env_kwargs": dict(
            sample_dir="./inference_dataset/partial_datasets/",
            splitBy="unc",
            radius=5,
            data_root="./inference_dataset/partial_datasets/",
        ),
        "seed_key": "seed",
        "gt_strategy": None,
        "gt_kwargs": {},
        "extra_state": "current_description",
    },
    "referring_dot_pointing/hard": {
        "env_kwargs": dict(
            sample_dir="./inference_dataset/partial_datasets/",
            splitBy="unc",
            radius=5,
        ),
        "seed_key": "seed",
        "gt_strategy": None,
        "gt_kwargs": {},
        "extra_state": "current_description",
    },
    "sliding_block/easy": {
        "env_kwargs": dict(
            num_shuffle_moves=30,
        ),
        "seed_key": None,
        "gt_strategy": None,
        "gt_kwargs": {},
        "extra_state": None,
    },
    "sliding_block/hard": {
        "env_kwargs": dict(
            num_shuffle_moves=90,
        ),
        "seed_key": None,
        "gt_strategy": None,
        "gt_kwargs": {},
        "extra_state": None,
    },
    "maze_2d/easy": {
        "env_kwargs": dict(
            maze_width=9,
            maze_height=9,
            # render_mode="rgb_array",
        ),
        "seed_key": "seed",
        "gt_strategy": None,
        "gt_kwargs": {},
        "extra_state": None,
    },
    "maze_2d/hard": {
        "env_kwargs": dict(
            maze_width=11,
            maze_height=11,
            # render_mode="rgb_array",
        ),
        "seed_key": "seed",
        "gt_strategy": None,
        "gt_kwargs": {},
        "extra_state": None,
    },
    "maze_3d/easy": {
        "env_kwargs": dict(
            maze_width=7,
            maze_height=7,
            render_mode="rgb_array",
        ),
        "seed_key": "seed",
        "gt_strategy": None,
        "gt_kwargs": {},
        "extra_state": "maze_map",
    },
    "maze_3d/hard": {
        "env_kwargs": dict(
            maze_width=9,
            maze_height=9,
            render_mode="rgb_array",
        ),
        "seed_key": "seed",
        "gt_strategy": None,
        "gt_kwargs": {},
        "extra_state": "maze_map",
    },
    "video_unshuffle/easy": {
        "factory": "VideoUnshuffleEnv",
        "env_kwargs": dict(
            root_dir="./inference_dataset/partial_datasets/ssv2",
            num_frames=4,
            sampling_strategy="salient",
            min_frame_diff=0.15,
            max_frames_to_analyze=100,
        ),
        "seed_key": "seed",
        "gt_strategy": None,
        "gt_kwargs": {},
        "extra_state": None,
    },
    "video_unshuffle/hard": {
        "factory": "VideoUnshuffleEnv",
        "env_kwargs": dict(
            root_dir="./inference_dataset/partial_datasets/ssv2",
            num_frames=5,
            sampling_strategy="salient",
            min_frame_diff=0.15,
            max_frames_to_analyze=100,
        ),
        "seed_key": "seed",
        "gt_strategy": None,
        "gt_kwargs": {},
        "extra_state": None,
    },
    "zoom_in_puzzle/easy": {
        "env_kwargs": dict(
            sample_dir="./inference_dataset/partial_datasets/zoomin",
            min_zoom_level=0.75,
            zoom_gap=0.75,
            zoom_std=0.2,
            nested=True,
            num_zoom_views=4,
        ),
        "seed_key": "seed",
        "gt_strategy": "swap",
        "gt_kwargs": {},
        "extra_state": None,
    },
    "zoom_in_puzzle/hard": {
        "env_kwargs": dict(
            sample_dir="./inference_dataset/partial_datasets/zoomin",
            min_zoom_level=0.75,
            zoom_gap=0.75,
            zoom_std=0.2,
            nested=True,
            num_zoom_views=5,
        ),
        "seed_key": "seed",
        "gt_strategy": "swap",
        "gt_kwargs": {},
        "extra_state": None,
    },
    "patch_reassembly/easy": {
        "env_kwargs": dict(
            grid_size=(6, 6),
            num_patches=5,
        ),
        "seed_key": "seed",
        "gt_strategy": None,
        "gt_kwargs": {},
        "extra_state": None,
    },
    "patch_reassembly/hard": {
        "env_kwargs": dict(
            grid_size=(8, 8),
            num_patches=6,
        ),
        "seed_key": "seed",
        "gt_strategy": None,
        "gt_kwargs": {},
        "extra_state": None,
    },
    "fetch_pick_and_place/easy": {
        "env_kwargs": dict(
            reward_type="sparse",
            render_mode="rgb_array",
            use_follow_camera=True,
            follow_cam_azimuth=200.0,
            follow_cam_elevation=-65.0,
            follow_cam_distance=0.36,
            camera_default_distance=1.75,
        ),
        "seed_key": None,
        "gt_strategy": None,
        "gt_kwargs": {},
        "extra_state": None,
    },
    "fetch_pick_and_place/hard": {
        "env_kwargs": dict(
            reward_type="sparse",
            render_mode="rgb_array",
            use_follow_camera=True,
            follow_cam_azimuth=200.0,
            follow_cam_elevation=-65.0,
            follow_cam_distance=0.36,
            camera_default_distance=1.75,
        ),
        "seed_key": None,
        "gt_strategy": None,
        "gt_kwargs": {},
        "extra_state": None,
    },
    "fetch_reach/easy": {
        "env_kwargs": dict(
            reward_type="sparse",
            render_mode="rgb_array",
            use_follow_camera=True,
            follow_cam_azimuth=200.0,
            follow_cam_elevation=-65.0,
            follow_cam_distance=0.36,
            camera_default_distance=1.75,
        ),
        "seed_key": None,
        "gt_strategy": None,
        "gt_kwargs": {},
        "extra_state": None,
    },
    "fetch_reach/hard": {
        "env_kwargs": dict(
            reward_type="sparse",
            render_mode="rgb_array",
            use_follow_camera=True,
            follow_cam_azimuth=200.0,
            follow_cam_elevation=-65.0,
            follow_cam_distance=0.36,
            camera_default_distance=1.75,
        ),
        "seed_key": None,
        "gt_strategy": None,
        "gt_kwargs": {},
        "extra_state": None,
    },
    "counting/easy": {
        "env_kwargs": dict(
            annotation_file="./inference_dataset/partial_datasets/counting/lvis_v1_train.json",
            sample_dir="./inference_dataset/partial_datasets/counting",
            max_count=20,
            min_count=2,
            radius=5,
        ),
        "seed_key": "seed",
        "gt_strategy": None,
        "gt_kwargs": {},
        "extra_state": "category_name",
    },
    "counting/hard": {
        "env_kwargs": dict(
            annotation_file="./inference_dataset/partial_datasets/counting/lvis_v1_train.json",
            sample_dir="./inference_dataset/partial_datasets/counting",
            radius=5,
            max_count=30,
            min_count=5,
        ),
        "seed_key": "seed",
        "gt_strategy": None,
        "gt_kwargs": {},
        "extra_state": "category_name",
    },
}

